# Generated by Django 4.0.5 on 2022-10-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movieshots_options_alter_actor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='media/', verbose_name='Постер'),
        ),
    ]
